### ISSUE TITLE
not functionning on Kodi 18

### ISSUE THREAD

**Issue by sitronet** [bossanova808/repository.bossanova808#11]
Hello
After a while, i tried the Xsqueeze add-on on my new LibreElec (kodi 18) , il seems that's not working well (in fact not working at all ;)) , I post below the log finded in ~/storage/kodi/temp/kodi.log 
Could you do something in the code ? thanks

```
2019-04-21 15:02:32.378 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference separator setting in old setting condition "!eq
( -2,false)" for "player"
2019-04-21 15:02:32.379 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -2,false)" of old setting
 definition for "player"
2019-04-21 15:02:32.380 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -10; absolute index: -
3) in another category in old setting condition "!eq( -10,false)" for "slaveargs"
2019-04-21 15:02:32.381 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -10,false)" of old settin
g definition for "slaveargs"
2019-04-21 15:02:32.382 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -11; absolute index: -
3) in another category in old setting condition "!eq( -11,false)" for "liteargs"
2019-04-21 15:02:32.382 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -11,false)" of old settin
g definition for "liteargs"
2019-04-21 15:03:10.527 T:1937293984   ERROR: Control 55 in window 10001 has been asked to focus, but it can't
2019-04-21 15:03:12.225 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference separator setting in old setting condition "!eq
( -2,false)" for "player"
2019-04-21 15:03:12.225 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -2,false)" of old setting
 definition for "player"
2019-04-21 15:03:12.228 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -10; absolute index: -
3) in another category in old setting condition "!eq( -10,false)" for "slaveargs"
2019-04-21 15:03:12.228 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -10,false)" of old settin
g definition for "slaveargs"
2019-04-21 15:03:12.229 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -11; absolute index: -
3) in another category in old setting condition "!eq( -11,false)" for "liteargs"
2019-04-21 15:03:12.229 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -11,false)" of old settin
g definition for "liteargs"
2019-04-21 15:03:12.292 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### XSqueeze Chooser (Author: bossanova808) Starting ...
2019-04-21 15:03:12.293 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### uname is: ('Linux', 'LibreELEC', '4.19.23', '#1 Wed Feb 20 23:37
:35 EST 2019', 'armv6l', '')
2019-04-21 15:03:12.294 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### System is arm
2019-04-21 15:03:12.295 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### Kodi Version #: 18.1
2019-04-21 15:03:12.296 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### Kodi Version  : L*
2019-04-21 15:03:12.298 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### Addon arguments as: ['plugin://plugin.program.xsqueezechooser/',
 '2', '', 'resume:false']
2019-04-21 15:03:12.305 T:1552937840   ERROR: Traceback (most recent call last):
2019-04-21 15:03:12.305 T:1552937840   ERROR:   File "/storage/.kodi/addons/plugin.program.xsqueezechooser/default.py", line 577, in <module>
2019-04-21 15:03:12.310 T:1552937840   ERROR:     buildRootListing()
2019-04-21 15:03:12.311 T:1552937840   ERROR:   File "/storage/.kodi/addons/plugin.program.xsqueezechooser/default.py", line 94, in buildRootLi
sting
2019-04-21 15:03:12.312 T:1552937840   ERROR:     addNode("New Music (latest 50 albums)","",NEW_MUSIC,"")
2019-04-21 15:03:12.312 T:1552937840   ERROR:   File "/storage/.kodi/addons/plugin.program.xsqueezechooser/default.py", line 37, in addNode
2019-04-21 15:03:12.313 T:1552937840   ERROR:     "&cmd="+urllib.quote_plus(cmd)
2019-04-21 15:03:12.317 T:1552937840   ERROR:   File "/usr/lib/python2.7/urllib.py", line 1302, in quote_plus
2019-04-21 15:03:12.319 T:1552937840   ERROR: TypeError: argument of type 'NoneType' is not iterable
2019-04-21 15:03:12.337 T:1552937840  NOTICE: ### XSqueeze Chooser - 0.2.2 ### XSqueeze Chooser (Author: bossanova808) Exiting ....
2019-04-21 15:03:14.101 T:1552937840   ERROR: Unable to find plugin
2019-04-21 15:03:14.101 T:1552937840   ERROR: GetDirectory - Error getting plugin://
2019-04-21 15:03:14.102 T:1937293984   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2019-04-21 15:03:22.026 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference separator setting in old setting condition "!eq
( -2,false)" for "player"
2019-04-21 15:03:22.026 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -2,false)" of old setting
 definition for "player"
2019-04-21 15:03:22.028 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -10; absolute index: -
3) in another category in old setting condition "!eq( -10,false)" for "slaveargs"
2019-04-21 15:03:22.028 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -10,false)" of old settin
g definition for "slaveargs"
2019-04-21 15:03:22.029 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -11; absolute index: -
3) in another category in old setting condition "!eq( -11,false)" for "liteargs"
2019-04-21 15:03:22.029 T:1937293984 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -11,false)" of old settin
g definition for "liteargs"
2019-04-21 15:03:25.358 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference separator setting in old setting condition "!eq
( -2,false)" for "player"
2019-04-21 15:03:25.359 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -2,false)" of old setting
 definition for "player"
2019-04-21 15:03:25.361 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -10; absolute index: -
3) in another category in old setting condition "!eq( -10,false)" for "slaveargs"
2019-04-21 15:03:25.362 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -10,false)" of old settin
g definition for "slaveargs"
2019-04-21 15:03:25.362 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -11; absolute index: -
3) in another category in old setting condition "!eq( -11,false)" for "liteargs"
2019-04-21 15:03:25.362 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -11,false)" of old settin
g definition for "liteargs"
2019-04-21 15:03:25.400 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference separator setting in old setting condition "!eq
( -2,false)" for "player"
2019-04-21 15:03:25.405 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -2,false)" of old setting
 definition for "player"
2019-04-21 15:03:25.407 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -10; absolute index: -
3) in another category in old setting condition "!eq( -10,false)" for "slaveargs"
2019-04-21 15:03:25.411 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -10,false)" of old settin
g definition for "slaveargs"
2019-04-21 15:03:25.411 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: cannot reference setting (relative index: -11; absolute index: -
3) in another category in old setting condition "!eq( -11,false)" for "liteargs"
2019-04-21 15:03:25.412 T:1552937840 WARNING: CAddonSettings[script.xsqueeze]: failed to parse enable condition "!eq( -11,false)" of old settin
g definition for "liteargs"
2019-04-21 15:03:26.177 T:1552937840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<
--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named cec
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.xsqueeze/default.py", line 26, in <module>
                                                from NowPlayingWindow import *
                                              File "/storage/.kodi/addons/script.xsqueeze/resources/lib/classes/NowPlayingWindow.py", line 13, 
in <module>
                                                import cec
                                            ImportError: No module named cec
                                            -->End of Python script error report<--
```

**Comment by bossanova808** [comment]
This is a bug with Kodi/packaging - the CEC package is missing on your system.  They should resolve that...so ask on the kodi forums in the appropriate platform section why that is missing I guess.

(In general, XSqueeze will not be working on further (there's the newer 'Squeezebox for Kodi' thing these days)
